const foodOptions = [
  "Mindys",
  "Chipotle",
  "Chick-fil-A",
  "McDonalds",
  "Taco Bell",
  "Wendys",
  "Burger King",
  "KFC",
  "Popeyes",
  "Subway",
  "Pizza Hut",
  "Dominos",
  "Nancy's Pizza",
  "Jersey Mikes",
  "Potbelly",
  "Buffalo Wild Wings",
  "Panda Express",
  "Five Guys",
  "LeftOvers",
  "Home Cooked",
  "FFY",
  "Amanda Chooses",
  "Alec Chooses",
  "Michael Chooses",
  "Laura Chooses",
];

export default foodOptions;
